theme: jekyll-text-theme
text_skin: default # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: default # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"
baseurl: ""
title: Site title

author:
  type: person
  name: Erkki Esimerkki

comments:
  provider: false

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

include:
- _pages
